/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef ZURI_STD_COLLECTIONS_LIB_TYPES_H
#define ZURI_STD_COLLECTIONS_LIB_TYPES_H

#include <cstdint>

enum class StdCollectionsTrap : uint32_t {
    HASHMAP_ALLOC,
    HASHMAP_CTOR,
    HASHMAP_SIZE,
    HASHMAP_CONTAINS,
    HASHMAP_GET,
    HASHMAP_PUT,
    HASHMAP_REMOVE,
    HASHMAP_CLEAR,
    HASHMAP_ITER,
    OPTION_ALLOC,
    OPTION_CTOR,
    OPTION_GET,
    OPTION_IS_EMPTY,
    TREEMAP_ALLOC,
    TREEMAP_CTOR,
    TREEMAP_SIZE,
    TREEMAP_CONTAINS,
    TREEMAP_GET,
    TREEMAP_PUT,
    TREEMAP_REMOVE,
    TREEMAP_CLEAR,
    TREEMAP_ITER,
    TREESET_ALLOC,
    TREESET_CTOR,
    TREESET_SIZE,
    TREESET_CONTAINS,
    TREESET_ADD,
    TREESET_REMOVE,
    TREESET_CLEAR,
    TREESET_ITERATE,
    TREESET_ITERATOR_ALLOC,
    TREESET_ITERATOR_NEXT,
    TREESET_ITERATOR_VALID,
    VECTOR_ALLOC,
    VECTOR_CTOR,
    VECTOR_SIZE,
    VECTOR_AT,
    VECTOR_APPEND,
    VECTOR_INSERT,
    VECTOR_UPDATE,
    VECTOR_REMOVE,
    VECTOR_CLEAR,
    VECTOR_ITERATE,
    VECTOR_ITERATOR_ALLOC,
    VECTOR_ITERATOR_NEXT,
    VECTOR_ITERATOR_VALID,
    LAST_,
};

#endif // ZURI_STD_COLLECTIONS_LIB_TYPES_H
