/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef ZURI_STD_SYSTEM_LIB_TYPES_H
#define ZURI_STD_SYSTEM_LIB_TYPES_H

#include <cstdint>

enum class StdSystemTrap : uint32_t {
    ATTR_ALLOC,
    ELEMENT_ALLOC,
    FUTURE_ALLOC,
    FUTURE_CTOR,
    FUTURE_RESOLVE,
    FUTURE_REJECT,
    FUTURE_CANCEL,
    APPEND_OPERATION_ALLOC,
    INSERT_OPERATION_ALLOC,
    UPDATE_OPERATION_ALLOC,
    REPLACE_OPERATION_ALLOC,
    EMIT_OPERATION_ALLOC,
    PORT_RECEIVE,
    PORT_SEND,
    QUEUE_ALLOC,
    QUEUE_POP,
    QUEUE_PUSH,
    ACQUIRE,
    AWAIT,
    GET_RESULT,
    SLEEP,
    LAST_,
};

#endif // ZURI_STD_SYSTEM_LIB_TYPES_H
